require('../../../vendor/assets/javascripts/flot/jquery.canvaswrapper.js')
require('../../../vendor/assets/javascripts/flot/jquery.colorhelpers.js')
require('../../../vendor/assets/javascripts/flot/jquery.flot.js')
require('../../../vendor/assets/javascripts/flot/jquery.flot.browser.js')
require('../../../vendor/assets/javascripts/flot/jquery.flot.saturated.js')
require('../../../vendor/assets/javascripts/flot/jquery.flot.drawSeries.js')
require('../../../vendor/assets/javascripts/flot/jquery.event.drag.js')
require('../../../vendor/assets/javascripts/flot/jquery.flot.hover.js')
require('../../../vendor/assets/javascripts/flot/jquery.flot.uiConstants.js')
require('../../../vendor/assets/javascripts/flot/jquery.flot.selection.js')
require('../../../vendor/assets/javascripts/bootstrap-slider')

require('./range_limit_shared')
require('./range_limit_plotting')
require('./range_limit_slider')
require('./range_limit_distro_facets')
